// Generated by https://quicktype.io

export interface Developer {
  githubUrl: string;
  id: string;
  linkedinUrl: string;
  name: string;
  profileDescription: string;
  publishedAt: string;
  updatedAt: string;
  email: string;
  extraGithubUrl: string;
  stack: string[];
  shortDesc: string;
}
