// Generated by https://quicktype.io

export interface Developer {
  githubUrl: string;
  id: string;
  linkedinUrl: string;
  name: string;
  profileDescription: string;
  publishedAt: string;
  updatedAt: string;
  email: string;
  extraGithubUrl: string;
  stack: string[];
  shortDesc: string;
}
// Generated by https://quicktype.io

export type AllProjects = Project[];

export interface Project {
  id: string;
  isActive: boolean;
  isDeployed: boolean;
  projectDemoVideoUrl: null;
  projectDeployedVersion: string;
  projectDescription: string;
  projectGithubLink: string;
  projectLastUpdated: null;
  projectTitle: string;
  stack: string[];
  publishedAt: null;
  projectThumbnail: { url: string };
  projectVideo: { url: string };
  projectCover: { url: string };
}
